Merge Testing Into Develop
globe-and-citizen/Celebrity-Fanalyzer pull request #115
Opened 2023-02-19 16:26 UTC by stravid87

## Description

INSERT YOUR DESCRIPTION HERE.

---

Before requesting a review of this Pull Request, I certify that I have tested the following items in the application and all have passed my local tests without any side effects:

- [x] Logout and login;
- [x] Navigation between pages;
- [x] Creation of a new prompt;
- [x] Creation of a new entry;
- [x] Like and Dislike button;
- [x] Share button;
- [x] Exclusion of the newly created prompt;
- [!] Deletion of the newly created entry;

---

##DESCRIPTIONS
Here is the testing branch. It's now ready for review. The problem with deleting the entry persists but I don't want this to delay our use of the testing branch. As soon as we get real users (I've started to reach out), the development and feature requests are doing to come hard and fast. Too hard and too fast. So I feel that good test coverage, an robust CI/CD pipeline are necessary before we get real users.

@arnonrdp can you work your magic now to add the Github action?
@hermannleboss can you modify the Bargraph test suite to add the necessary props and then build out the tests
@NJavokhir can you use the test files present to start building tests for commenting?

Amazing guys! We're so close to entering the virtuous dev/ops cycle that EVERY Silicon Valley book ever talks about. All those start-ups in the Valley would be proud!

2023-02-20 17:29 UTC, arnonrdp commented
Great to see the tests start to work.

Absolutely! I'll stick with the settings on GitHub Actions.

2023-02-21 18:26 UTC, arnonrdp commented
@globe-and-citizen/team-1-test, everything seems to be working perfectly.

In my penultimate [commit](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/pull/115/commits/a261739f8b5973498431fb084945df7e194422a2) I removed Hosting as I know it will not be used at this time. However, I wonder if there isn't anything else that can/should be removed.

For example, I've noticed that those test components have been removed, but I'm wondering if the [`/coverage`](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/tree/testing_for_merge/coverage) folder is needed or if there's something else we don't need right now.

2023-02-22 09:52 UTC, hermannleboss requested changes

2023-02-22 09:52 UTC, hermannleboss commented on .gitignore
> +ui-debug.log
```suggestion
ui-debug.log
/coverage
```

2023-02-22 09:52 UTC, hermannleboss commented on .gitignore
> +ui-debug.log
You don't need to add coverage output in git-versioned files.

2023-02-23 13:20 UTC, stravid87 commented
> @globe-and-citizen/team-1-test, everything seems to be working perfectly.
> 
> In my penultimate [commit](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/pull/115/commits/a261739f8b5973498431fb084945df7e194422a2) I removed Hosting as I know it will not be used at this time. However, I wonder if there isn't anything else that can/should be removed.
> 
> For example, I've noticed that those test components have been removed, but I'm wondering if the [`/coverage`](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/tree/testing_for_merge/coverage) folder is needed or if there's something else we don't need right now.

@hermannleboss I have not dived into Code Coverage yet. I remains on my ToDo. Hermann, what are you thoughts?

2023-02-23 15:22 UTC, hermannleboss commented
I think we do not need it, because it will change depending on testing we create and it will create many files to track

On févr. 23 2023, at 1:20 pm, stravid87 ***@***.***> wrote:
>
>
> > @globe-and-citizen/team-1-test (https://github.com/orgs/globe-and-citizen/teams/team-1-test), everything seems to be working perfectly.
> > In my penultimate commit (https://github.com/globe-and-citizen/Celebrity-Fanalyzer/pull/115/commits/a261739f8b5973498431fb084945df7e194422a2) I removed Hosting as I know it will not be used at this time. However, I wonder if there isn't anything else that can/should be removed.
> > For example, I've noticed that those test components have been removed, but I'm wondering if the /coverage (https://github.com/globe-and-citizen/Celebrity-Fanalyzer/tree/testing_for_merge/coverage) folder is needed or if there's something else we don't need right now.
> @hermannleboss (https://github.com/hermannleboss) I have not dived into Code Coverage yet. I remains on my ToDo. Hermann, what are you thoughts?
>
> —
> Reply to this email directly, view it on GitHub (https://github.com/globe-and-citizen/Celebrity-Fanalyzer/pull/115#issuecomment-1441772809), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AG44EHQVOEIJ2K3KR7NUJLDWY5P3XANCNFSM6AAAAAAVBBPUFE).
> You are receiving this because you were mentioned.
>

2023-03-01 17:46 UTC, stravid87 reviewed
Simple change to make it work.

2023-03-01 18:18 UTC, arnonrdp approved these changes

2023-03-01 18:18 UTC, merged