[Feature] Created public profile page
globe-and-citizen/Celebrity-Fanalyzer pull request #230
Opened 2023-06-02 14:54 UTC by arnonrdp

- Created new public profile page for all users.

Resolve #223

2023-06-07 12:58 UTC, stravid87 requested changes
Authors page looks great -- too easy for you I think!
I tried: changing my photo; changing my social media handles; changing my bio -- all works. 
Looks good on mobile and on desktop. It's only June 7th though so let's get the two testing runs to work first and add at least, a testing template for the profile page. I'll fix the currently broken Vitest file. Can you add a user.spec.js? One simple test. Adequate for now I'm thinking.

2023-06-07 14:42 UTC, arnonrdp commented on src/pages/PublicProfilePage.vue
> +onMounted(async () => {
You are right.
I need to improve the query to the user. Let me focus on it today.

2023-06-07 14:43 UTC, arnonrdp commented on src/router/routes.js
> +        path: 'fan/:username',
# 🎯

2023-06-07 14:48 UTC, arnonrdp commented on src/components/Posts/ThePost.vue
> +      <section v-if="post?.author" class="flex items-center no-wrap q-pa-md" @click="openProfile">
We can do that, but it wouldn't be a profile page.
It would look something like a profile dialog.

2023-06-07 14:51 UTC, arnonrdp commented
> @arnonrdp I think that Cypress commenting we can ignore. The test for login-logout is probably worth fixing now.

Alright, by the way feel free to commit update on tests in this branch.

2023-06-08 03:50 UTC, stravid87 commented on src/components/Posts/ThePost.vue
> +      <section v-if="post?.author" class="flex items-center no-wrap q-pa-md" @click="openProfile">
You mean like a tool tip? Something that pop us when the user hovers?

2023-06-08 03:54 UTC, stravid87 commented on src/pages/PublicProfilePage.vue
> +  await userStore.getUserByUidOrUsername(router.currentRoute.value.params.username).then((res) => (user.value = res))
nice.

2023-06-08 15:42 UTC, stravid87 commented
@arnonrdp 
Please take a look at line 162 of prompts.js specifically. I added an "await" in front of Promise.All(...). Though I doubt this will break the site, it is a change to one of a Pinia store and therefore may have ramifications for testing. 

Before we merge, can you add a single Vitest `<store>.spec` to our repo with just a single test. If you take a look at the vitest files I added, it should be quite straight forward because you can use the other specs as templates.

@hermannleboss, can you figure out what is wrong with our Cypress test on this branch?

2023-06-08 17:55 UTC, arnonrdp commented on src/components/Posts/ThePost.vue
> +      <section v-if="post?.author" class="flex items-center no-wrap q-pa-md" @click="openProfile">
I meant like a popup (`q-dialog`).

Yes, we can add links to all the places where we have a picture of the user and that way we will redirect to their profile.

We just can't have it in `PublicProfilePage.vue` as that is the destination and not the source.

I will include the links to the profile in the respective sources.

2023-06-08 18:10 UTC, hermannleboss commented
> @arnonrdp Please take a look at line 162 of prompts.js specifically. I added an "await" in front of Promise.All(...). Though I doubt this will break the site, it is a change to the Pinia store and therefore may have ramifications outside of testing.

I add a fix, let see if the CI will pass

2023-06-08 18:11 UTC, arnonrdp commented
> > @arnonrdp Please take a look at line 162 of prompts.js specifically. I added an "await" in front of Promise.All(...). Though I doubt this will break the site, it is a change to the Pinia store and therefore may have ramifications outside of testing.
> 
> I add a fix, let see if the CI will pass

Thanks for that, Hermann! 💪

2023-06-08 18:39 UTC, arnonrdp commented
@stravid87, it is all done.

Can you merge it?

2023-06-09 03:42 UTC, stravid87 commented
> @stravid87, it is all done.
> 
> Can you approve and merge it?

We've got to get into the habit of building out the test suites as we go -- just add one more spec file. The Public Profile Page Pulls from these four stores. 

- const entryStore = useEntryStore()
- const errorStore = useErrorStore()
- const promptStore = usePromptStore()
- const userStore = useUserStore()

Just add a single test to Vitest or Cypress. It could be as simple as scaffolding the ErrorStore.

2023-06-09 03:44 UTC, stravid87 requested changes
We're regressing on our test coverage so, as per our rule, we need to add testing before we get this merged: Vitest or Cypress.

2023-06-09 13:04 UTC, arnonrdp commented
> > @stravid87, it is all done.
> > Can you approve and merge it?
> 
> We've got to get into the habit of building out the test suites as we go -- just add one more spec file. The Public Profile Page Pulls from these four stores.
> 
> * const entryStore = useEntryStore()
> * const errorStore = useErrorStore()
> * const promptStore = usePromptStore()
> * const userStore = useUserStore()
> 
> Just add a single test to Vitest or Cypress. It could be as simple as scaffolding the ErrorStore.

Sorry, I missed that. I am on it.

2023-06-10 02:58 UTC, stravid87 approved these changes

2023-06-10 03:00 UTC, merged