Feature/quick redirection
globe-and-citizen/Celebrity-Fanalyzer pull request #293
Opened 2023-08-05 10:34 UTC by hermannleboss

## Resolve quick redirection on prompt, entry and public profile page
 Resolve #292

2023-08-05 12:57 UTC, arnonrdp requested changes
@hermannleboss, errors popped up here:

https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/0876c02d-7fb1-485f-a8dc-d2a1fe7cbc28

2023-08-05 13:05 UTC, hermannleboss commented
> @hermannleboss, errors popped up here:
> 
>  Access.Entry-appletv.mp4

OK i'm on it

2023-08-05 18:47 UTC, hermannleboss commented
> > @hermannleboss, errors popped up here:
> > Access.Entry-appletv.mp4
> 
> OK i'm on it

@arnonrdp It's done

2023-08-08 19:37 UTC, arnonrdp approved these changes

2023-08-08 19:37 UTC, merged