Stravid87/reading time
globe-and-citizen/Celebrity-Fanalyzer pull request #30
Opened 2022-11-25 17:39 UTC by stravid87

Gah... I'm out of time. To really dig into some of the nuances between repos.
The primary function is very straight forwarded and can be added to any <script setup> </script> tags in the future to estimate reading time. Hard coded constants (like 238 as the reading time / minute) can be easily tweaked.

```
function giveReadingTime(description) {
  let stringArr = description.split(' ')
  let adjustment = 0
  stringArr = stringArr.filter((el) => {
    //removes anything that's an html tag
    if (el.indexOf('<') == -1) {
      return el
    } else {
      adjustment++
    }
  })
```

2022-11-25 18:49 UTC, arnonrdp requested changes
Your PR have conflicts, it is important to update your branch with **Develop** branch before proceed.

Also, I noticed you are trying to solve more than one issue. For this, you have two options:
* Open a PR that solves 2 issues; or
* Open a PR that solve 1 issue.

It is not a good practice to solve partially a issue.

Once this is your first branch and PR, I would try to solve only the issue #27.

2022-12-03 12:35 UTC, stravid87 commented
Got it. Thanks for the feedback. I'll work on this today.

2022-12-03 15:19 UTC, arnonrdp commented
@stravid87 Let me know if you have any problems resolving conflicts.

2022-12-05 18:50 UTC, arnonrdp approved these changes

2022-12-05 18:52 UTC, merged