update the way people write entries
globe-and-citizen/Celebrity-Fanalyzer pull request #410
Opened 2024-07-02 12:46 UTC by sana7044

update the way people write entries

2024-07-03 12:45 UTC, marclupanc requested changes
Nice PR. Some minor suggestions from me 👍

2024-07-03 12:45 UTC, marclupanc commented on src/components/Admin/TableEntry.vue
> +          v-if="props.row.isWinner != true && userStore.isEditorOrAbove"
Comparison props.row.isWinner != true may cause unexpected type coercion. Maybe replace it with "!=="

2024-07-03 12:45 UTC, marclupanc commented on src/components/Admin/TableEntry.vue
>            v-if="props.row.isWinner == true"
Maybe replace as above.

2024-07-03 12:45 UTC, marclupanc commented on src/components/shared/TheEntries.vue
> +      <q-icon name="add" size="30px" @click="openEntryDialog()"><q-tooltip>Add entries</q-tooltip></q-icon>
I would suggest adding "cursor: pointer" to the + button for better user experience

2024-07-04 14:48 UTC, arnonrdp approved these changes

2024-07-04 14:48 UTC, merged