Feature/year month navigation
globe-and-citizen/Celebrity-Fanalyzer pull request #44
Opened 2022-12-09 19:03 UTC by hermannleboss

Using id instead of using slug in the prompt page routing

![image](https://user-images.githubusercontent.com/28951070/206776767-a87778b3-bf91-4acf-98d2-6b0a9dc842fb.png)

Close #33

2022-12-10 12:58 UTC, arnonrdp commented
Hey @hermannleboss, aliases didn't work well?
Isn't it possible to use the same component for `MonthArchivePage.vue` and `PromptPage.vue`?

2022-12-10 12:59 UTC, hermannleboss commented
Explain

2022-12-10 15:00 UTC, arnonrdp commented
> Explain

Please check: https://router.vuejs.org/guide/essentials/redirect-and-alias.html#alias

We use aliases so that the user can access the same destination with different URLs.

Furthermore, it is also possible to reuse `PrompPage.vue` as the Component to be rendered for this URL.

In the end it would be something like:
```js
{
   path: 'prompt/:id',
   alias: ':year(\\d{4})/:month',
   component: () => import('pages/PromptPage.vue')
}
```

This way, the user will be able to access the page through `year/month` or `prompt/slug`.
I even believe that for sharing it is better that we use the slug, but that is another point.

2022-12-10 15:02 UTC, arnonrdp commented on src/components/ItemCard.vue
> +        <p class="q-mb-none q-ml-sm text-body1" v-if="item.author.displayName">
I already fixed the bug we were having here.

You can `git pull` it from `develop` branch

2022-12-10 15:04 UTC, arnonrdp requested changes
Please check: https://router.vuejs.org/guide/essentials/redirect-and-alias.html#alias

We use aliases so that the user can access the same destination with different URLs.

Furthermore, it is also possible to reuse `PrompPage.vue` as the Component to be rendered for this URL.

In the end it would be something like:
```js
{
   path: 'prompt/:id',
   alias: ':year(\\d{4})/:month',
   component: () => import('pages/PromptPage.vue')
}
```

This way, the user will be able to access the page through `year/month` or `prompt/slug`.
I even believe that for sharing it is better that we use the slug, but that is another point.

2022-12-10 22:11 UTC, hermannleboss commented
OK i see

2022-12-10 22:33 UTC, hermannleboss commented
It's OK, but i have an issue. 
The question is what parameter do we receive from the routing. 

```
   path: 'prompt/:id',
   alias: ':year(\\d{4})/:month',
```

We have `id` in `prompt/:id` and `year` and `month` in `year(\\d{4})/:month`

And with this parameter we should make the request to the store to find the right one.

2022-12-13 17:02 UTC, arnonrdp approved these changes

2022-12-13 17:03 UTC, merged