Enhancement:save crypto wallet address 533
globe-and-citizen/Celebrity-Fanalyzer pull request #549
Opened 2024-09-10 07:21 UTC by sana7044

Now, we can  add, update and delete the crypto wallet address.

2024-09-11 13:52 UTC, marclupanc requested changes
There is an issue with removing the wallet. 
When connecting the wallet for the first time, we can see that we can access the "Add advertisement".
Then after removing it from profile page, and saving the profile page and when trying to create an advertisement we are still able to do that. 
Then when going back to the profile page (and refreshing) we can see that the wallet address is still linked to our profile. Please see the video

https://vimeo.com/1008435431?share=copy

2024-09-12 07:25 UTC, sana7044 commented on src/components/Profile/ProfileTab.vue
> +        <!-- <q-btn
Yes, i removed the unused parts from this file.

2024-09-12 07:30 UTC, sana7044 commented on src/components/Profile/ProfileTab.vue
> +          Are you sure you want to {{ isUpdate ?'Update':'Set' }}:
Yes, i changed this type.

2024-09-12 07:46 UTC, sana7044 commented
I have fixed all issues regrading the change requests.

2024-09-13 12:59 UTC, marclupanc approved these changes

2024-09-13 12:59 UTC, merged