Feature/484 funding prompt flow
globe-and-citizen/Celebrity-Fanalyzer pull request #564
Opened 2024-09-12 13:00 UTC by achillegley

## Description

2024-09-13 12:54 UTC, marclupanc requested changes
Does this PR has all the changes from - #543 ?

2024-09-13 12:54 UTC, marclupanc commented on src/components/Admin/FundDepositCard.vue
> +        <!-- <q-input hide-hint label="Winner wallet address" maxlength="80" required v-model="_walletAddress" disable /> -->
Please remove all the commented code

2024-09-13 12:54 UTC, marclupanc commented on .gitignore
> +quasar.config.js
Why is it necessary to have this in gitignore?

2024-09-13 12:54 UTC, marclupanc commented on src/components/Advertiser/AdvertiserTable.vue
> +    //console.log('the result claimPayment result ====', result)
Please remove all the commented code

2024-09-13 12:54 UTC, marclupanc commented on src/components/Admin/ManagePromptsEntries.vue
> +  //console.log('the current wallet address ', currentWalletAddress)
Please remove all the commented code

2024-09-22 11:08 UTC, achillegley commented
> Does this PR has all the changes from - #543 ?

yes it has all my bad.

2024-09-23 07:55 UTC, marclupanc reviewed
Maybe we should disallow admins to delete prompts that currently have an entry with unclaimed payment? Currently if a user removes an prompt and user din't claim the payment will the user be able to claim it later?

2024-09-24 09:34 UTC, marclupanc approved these changes

2024-09-24 12:07 UTC, merged